package nutricentro.enums;

/** Eventos funcionales registrados en el timeline del turno. */
public enum AppointmentEventType {
    APPOINTMENT_CREATED,
    APPOINTMENT_UPDATED,
    STATUS_CHANGED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_PATIENT_PRESENT,
    APPOINTMENT_ABSENT,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_RESCHEDULED,
    WHATSAPP_MESSAGE_SENT,
    WHATSAPP_MESSAGE_FAILED,
    WHATSAPP_REMINDER_SENT,
    WHATSAPP_REMINDER_FAILED,
    WHATSAPP_RESPONSE_RECEIVED,
    WHATSAPP_RESPONSE_AMBIGUOUS,
    WHATSAPP_RESPONSE_INVALID,
    PROFESSIONAL_CHANGED,
    DATE_CHANGED,
    TIME_CHANGED
}
